### PR TITLE
✨ Optionally skip multichar emojis

### PR DESCRIPTION
**Pull request by pschmitt**
Since most terminals do not correctly display multicharacter emojis I'm proposing a flag to the preview action so that these do not get displayed.

TL;DR This allows to avoid the following (Konsole):

image

### CODE REVIEW

**Comment by pschmitt** [comment]
There seems to be something wrong with the tox config in this repo...

https://github.com/noahp/emoji-fzf/pull/14/checks?check_run_id=2012136084#step:3:269
https://github.com/noahp/emoji-fzf/pull/14/checks?check_run_id=2012136084#step:3:283
https://github.com/noahp/emoji-fzf/pull/14/checks?check_run_id=2012136084#step:3:343

**Comment by noahp** [comment]
> There seems to be something wrong with the tox config in this repo...
> 
> https://github.com/noahp/emoji-fzf/pull/14/checks?check_run_id=2012136084#step:3:269
> https://github.com/noahp/emoji-fzf/pull/14/checks?check_run_id=2012136084#step:3:283
> https://github.com/noahp/emoji-fzf/pull/14/checks?check_run_id=2012136084#step:3:343

yikes, yeah, it's broken. fixing asap!

**Review by noahp — APPROVED** [review]
this change looks good, thanks for making it! you should be able to rebase on `master` for working tests.

**Comment by pschmitt** [comment]
Done.

**Comment by noahp** [comment]
I tagged 0.5.0 and released to pypi with this change, thanks for doing it!

**Comment by pschmitt** [comment]
Nice 🤘

**Pull request merged**
